apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: gateway-api
    githubRelease:
      slug: kubernetes-sigs/gateway-api
      tag: "v1.4.1"
      assetNames:
        - standard-install.yaml
        - experimental-install.yaml
      disableAutoChecksumValidation: true
  - path: gateway-api-inference-extension
    githubRelease:
      slug: kubernetes-sigs/gateway-api-inference-extension
      tag: "v1.3.1"
      # according to https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/1611
      # we only need `manifests.yaml` for both stable and experimental CRD versions
      assetNames:
        - manifests.yaml
      disableAutoChecksumValidation: true
