apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: gateway-api
    githubRelease:
      slug: kubernetes-sigs/gateway-api
      tag: "v1.3.0"
      assetNames:
        - standard-install.yaml
        - experimental-install.yaml
      disableAutoChecksumValidation: true
