install:
  # Supports "standard", "experimental" and "" (empty string to disable rendering this CRD)
  gatewayclasses: standard
  # Supports "standard", "experimental" and "" (empty string to disable rendering this CRD)
  gateways: standard
  # Supports "standard", "experimental" and "" (empty string to disable rendering this CRD)
  grpcroutes: standard
  # Supports "standard", "experimental" and "" (empty string to disable rendering this CRD)
  httproutes: standard
  # Supports "standard", "experimental" and "" (empty string to disable rendering this CRD)
  referencegrants: standard
  # Supports "standard", "experimental" and "" (empty string to disable rendering this CRD)
  backendtlspolicies: standard
  # Supports "standard", "experimental" and "" (empty string to disable rendering this CRD)
  listenersets: "standard"

  # Supports "standard", "experimental" and "" (empty string to disable rendering this CRD)
  tcproutes: standard
  # Supports "standard", "experimental" and "" (empty string to disable rendering this CRD)
  tlsroutes: standard
  # Supports "standard", "experimental" and "" (empty string to disable rendering this CRD)
  udproutes: standard
  # Supports "experimental" and "" (empty string to disable rendering this CRD)
  xbackends: ""
  # Supports "experimental" and "" (empty string to disable rendering this CRD)
  xbackendtrafficpolicies: ""
  # Supports "experimental" and "" (empty string to disable rendering this CRD)
  xmeshes: ""

  # Supports "standard", "experimental" and "" (empty string to disable rendering this CRD)
  inferencepools: ""
  # Supports "experimental" and "" (empty string to disable rendering this CRD)
  inferenceobjectives: ""
  # Supports "experimental" and "" (empty string to disable rendering this CRD)
  inferencepoolimports: ""
  # Supports "experimental" and "" (empty string to disable rendering this CRD)
  inferencemodelrewrites: ""

  # Set to true to install the safe-upgrades ValidatingAdmissionPolicy and its binding
  admissionPolicies: true
