{{- if include "gateway-api-crds.selectedFiles" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gateway-api-crds.installerName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
  labels:
    {{- include "gateway-api-crds.labels" . | nindent 4 }}
{{- end }}
